server:
  port: 8443

spring:
  application:
    name: gateway-service
  profiles:
    active: dev # 表示开发环境
  jackson:
    time-zone: GMT+8
  redis:
    database: 0
    host: 47.110.79.125
    port: 6379
    password: zhujianxing959
  cloud:
    # 注册进 nacos Server
    nacos:
      discovery:
        server-addr: 47.99.131.144:8848
    ## GateWay配置
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: auth-service  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001  # 匹配后提供服务的路由地址
#          uri: http://localhost:9528
          uri: lb://auth-service
          predicates:
            - Path=/oauth/**  # 断言，路径相匹配的进行路由

        - id: api-test-service  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: lb://api-test-service
          predicates:
            - Path=/api/test/**  # 断言，路径相匹配的进行路由

        - id: auto-code
          uri: lb://auto-code
          predicates:
            - Path=/api/code/**

        - id: auto-doc
          uri: lb://auto-doc
          predicates:
            - Path=/api/doc/**

        - id: db-service
          uri: lb://db-service
          predicates:
            - Path=/api/db/**