# 服务端口号
server:
  port: 8445

# 服务名
spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://47.99.131.144:9411  # zipkin 地址
  sleuth:
    sampler:
      # 采样率值 介于0-1之间 ，1表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-bp167k6429i8drmq71o.mysql.rds.aliyuncs.com:3306/work_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: wanna959
    password: Zhujianxing959
  redis:
    database: 0
    host: 47.110.79.125
    port: 6379
    password: zhujianxing959
  mail:
    host: smtp.163.com
    port: 465
    username: wannazjx@163.com
    password: LQXFREUCTGRHLVQP
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.131.144:8848  # nacos作为服务注册中心
#        ip: 47.110.79.125
#        port: 8445

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.godx.cloud.entities  # 所有Entity 别名类所在包
  configuration:
    map-underscore-to-camel-case: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"