# 服务端口号
server:
  port: 9012

# 服务名
spring:
  application:
    name: auto-doc
  profiles:
    active: dev # 表示开发环境
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-bp167k6429i8drmq71o.mysql.rds.aliyuncs.com:3306/work_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: wanna959
    password: Zhujianxing959
  redis:
    database: 0
    host: 47.110.79.125
    port: 6379
    password: zhujianxing959
  mail:
    host: smtp.163.com
    port: 465
    username: wannazjx@163.com
    password: LQXFREUCTGRHLVQP
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  cloud:
    sentinel:
      transport:
        # 配置 Sentinel Dashboard 的地址
#        dashboard: 47.99.131.144:8080
        dashboard: localhost:8080
        # 默认8719 ，如果端口被占用，端口号会自动 +1，提供给 sentinel 的监控端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 47.99.131.144:8848
            dataId: auto-doc
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.godx.cloud.model  # 所有Entity 别名类所在包
  configuration:
    map-underscore-to-camel-case: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #单位毫秒
        readTimeout: 10000 #单位毫秒

